#!/usr/bin/env python3
"""Generate BATCH 06-10 (IDs 551-1000) - 450 remaining glossary terms"""

# BATCH 06: Sécurité & ERP (IDs 551-650) - 100 terms
batch_06 = [
    (551, 'Classement feu', 'Fire Rating', 'SÉCURITÉ', 'Classification résistance matériaux feu durée.', 'Fire resistance rating duration classification.'),
    (552, 'Compartimentage feu', 'Compartment', 'SÉCURITÉ', 'Division bâtiment limiter propagation feu.', 'Building fire spread containment division.'),
    (553, 'Contrôle densité', 'Density Check', 'SÉCURITÉ', 'Calcul nombre personnes surface.', 'Persons per area capacity calculation.'),
    (554, 'Itinéraire évacuation', 'Exit Route', 'SÉCURITÉ', 'Chemin sécurisé sortie urgence.', 'Secure path to emergency exit safely.'),
    (555, 'Portes coupe-feu', 'Fire Door', 'SÉCURITÉ', 'Porte fermeture automatique retard feu.', 'Auto-closing fire delay door.'),
    (556, 'Sprinkleurs', 'Sprinklers', 'SÉCURITÉ', 'Système arrosage automatique suppression incendie.', 'Automatic fire suppression spray system.'),
    (557, 'Détecteur chaleur', 'Heat Detector', 'SÉCURITÉ', 'Capteur température déclenchement alarme.', 'Temperature sensor alarm trigger point.'),
    (558, 'Gaz inerte CO2', 'Inert Gas', 'SÉCURITÉ', 'Étouffement oxygène suppression feu.', 'Oxygen removal fire suppression method.'),
    (559, 'Mousse suppresseur', 'Foam Agent', 'SÉCURITÉ', 'Produit surface feu refroidissement.', 'Fire surface cooling product.'),
    (560, 'Hydrant', 'Hydrant', 'SÉCURITÉ', 'Point eau rapidement accessible pompiers.', 'Accessible water point for firefighters.'),
    (561, 'Issue secours', 'Safety Exit', 'SÉCURITÉ', 'Sortie alternative dégagement secours.', 'Alternative exit emergency evacuation route.'),
    (562, 'Pont mobile', 'Bridge Link', 'SÉCURITÉ', 'Passerelle étages accès urgence.', 'Story level bridge emergency access.'),
    (563, 'Escalier urgence', 'Stairwell', 'SÉCURITÉ', 'Escalier réservé protection feu.', 'Fire-protected dedicated staircase access.'),
    (564, 'Rampe accès', 'Ramp', 'SÉCURITÉ', 'Pente douce mobilité réduite.', 'Gentle slope limited mobility access.'),
    (565, 'Signalisation sortie', 'Exit Sign', 'SÉCURITÉ', 'Panneaux lumineux sortie obligatoire.', 'Illuminated mandatory exit signage.'),
    (566, 'Bloc autonome', 'Auto Light', 'SÉCURITÉ', 'Éclairage secours batterie autonome.', 'Self-powered backup light battery unit.'),
    (567, 'Balisage au sol', 'Floor Marking', 'SÉCURITÉ', 'Marqueurs luminescents chemins obscurité.', 'Luminescent markers darkness visibility.'),
    (568, 'Photoluminescence', 'Glow Path', 'SÉCURITÉ', 'Peinture brillante obscurité sans électricité.', 'Glowing paint without electricity needed.'),
    (569, 'Matériaux ininflammable', 'Non-Flame', 'SÉCURITÉ', 'Isolants résistance feu classement.', 'Fire-resistant insulation classification test.'),
    (570, 'Laine minérale', 'Mineral Wool', 'SÉCURITÉ', 'Isolation anti-feu anti-bruit absorption.', 'Fire-insulating sound-dampening absorption.'),
    (571, 'Gysberplaque', 'Drywall Fire', 'SÉCURITÉ', 'Cloison résistance feu isolation.', 'Fire-resistant partition wall system.'),
    (572, 'Peinture anti-feu', 'Fireproof Paint', 'SÉCURITÉ', 'Revêtement limite propagation flamme.', 'Coating limits flame propagation rate.'),
    (573, 'Rideau anti-feu', 'Fire Curtain', 'SÉCURITÉ', 'Écran déploiement automatique prévention.', 'Auto-deploy screen fire prevention.'),
    (574, 'Câble blindé', 'Armoured Cable', 'SÉCURITÉ', 'Gaine acier protection thermique électrique.', 'Steel sheath thermal electrical protection.'),
    (575, 'Enduction feu', 'Fire Coating', 'SÉCURITÉ', 'Enduit protection acier bois.', 'Steel and wood protective coating.'),
    (576, 'Classification ERP A', 'ERP Type A', 'SÉCURITÉ', 'Petit bâtiment moins 50 personnes.', 'Small building under 50 person capacity.'),
    (577, 'Classification ERP J', 'ERP Type J', 'SÉCURITÉ', 'Structures spectacles amphithéâtres places.', 'Spectacle structure amphitheater seating.'),
    (578, 'Dossier sécurité', 'Safety File', 'SÉCURITÉ', 'Compilation documents conformité requise.', 'Compliance documentation compilation file.'),
    (579, 'Avis de faisabilité', 'Feasibility', 'SÉCURITÉ', 'Accord préalable pompiers événement.', 'Advance firefighter agreement event.'),
    (580, 'Étude dangers', 'Hazard Study', 'SÉCURITÉ', 'Analyse risques événement prévention.', 'Event risk analysis prevention plan.'),
    (581, 'Responsable sécurité', 'Safety Officer', 'SÉCURITÉ', 'Points focal incidents urgence.', 'Incident emergency focal point officer.'),
    (582, 'Coordinateur SST', 'Safety Coord', 'SÉCURITÉ', 'Santé sécurité travail coordination.', 'Work health safety coordination role.'),
    (583, 'Secouriste agréé', 'First Aider', 'SÉCURITÉ', 'Personnel formation secours certification.', 'Certified first aid personnel trained.'),
    (584, 'Infirmier présent', 'Medic Staff', 'SÉCURITÉ', 'Professionnel santé site présence.', 'Healthcare professional on-site presence.'),
    (585, 'Pompiers stationnés', 'Fire Crew', 'SÉCURITÉ', 'Équipe pompiers prête intervenir.', 'Firefighter team ready to respond.'),
    (586, 'Ambulance prête', 'Ambulance', 'SÉCURITÉ', 'Transport urgences équipé.', 'Emergency transport equipped vehicle.'),
    (587, 'Hélipad', 'Helipad', 'SÉCURITÉ', 'Zone atterrissage urgence aérienne.', 'Emergency air landing zone access.'),
    (588, 'Pont avancé', 'Advanced', 'SÉCURITÉ', 'Poste médical avancé triage.', 'Advanced medical post triage unit.'),
    (589, 'Secteur blessés', 'Casualty Area', 'SÉCURITÉ', 'Zone accueil urgences isolée.', 'Isolated emergency reception zone area.'),
    (590, 'Signal évacuation', 'Evacuation Alert', 'SÉCURITÉ', 'Alarme visuelle sonore urgence.', 'Visual and audio emergency alarm signal.'),
    (591, 'Exercice simulation', 'Drill', 'SÉCURITÉ', 'Test procédure validation personnel.', 'Procedure test personnel validation.'),
    (592, 'Débrief incident', 'Incident Review', 'SÉCURITÉ', 'Analyse post urgence leçons apprises.', 'Post-emergency analysis lessons learned.'),
    (593, 'Rapport incident', 'Incident Log', 'SÉCURITÉ', 'Documentation événement anormal survenu.', 'Abnormal event documentation log.'),
    (594, 'Assurance RC', 'Liability Ins', 'SÉCURITÉ', 'Couverture responsabilité civile tiers.', 'Third-party liability coverage policy.'),
    (595, 'Montant couverture', 'Coverage Amt', 'SÉCURITÉ', 'Limite maximum assurance prise.', 'Maximum insurance coverage policy limit.'),
    (596, 'Franchise assurance', 'Deductible', 'SÉCURITÉ', 'Montant charge sinistre assuré.', 'Insured charge amount per claim.'),
    (597, 'Police attestation', 'Proof Ins', 'SÉCURITÉ', 'Document attestant couverture assurance.', 'Document proving insurance coverage.'),
    (598, 'Délai déclaration', 'Claim Delay', 'SÉCURITÉ', 'Jours notification sinistre assureur.', 'Days to report claim to insurer.'),
    (599, 'Format rapport', 'Report Form', 'SÉCURITÉ', 'Modèle description incident requis.', 'Required incident report form template.'),
    (600, 'Photo preuve', 'Photographic Evidence', 'SÉCURITÉ', 'Clichés documentation sinistre.',
    'Incident photographic documentation proof.'),
    (601, 'Contact expert', 'Expert Contact', 'SÉCURITÉ', 'Évaluateur indépendant dommages assessment.', 'Independent damage assessor evaluator contact.'),
    (602, 'Procédure recours', 'Appeal Proc', 'SÉCURITÉ', 'Contester décision refus assureur.', 'Challenge insurer refusal decision appeal.'),
    (603, 'Calendrier jours', 'Workday Calc', 'SÉCURITÉ', 'Jours calendrier fermeture administratif.', 'Administrative closure calendar workday.'),
    (604, 'Arrêt activité', 'Activity Stop', 'SÉCURITÉ', 'Interruption service urgence fermeture.', 'Service interruption closure urgency.'),
    (605, 'Mesures correctives', 'Corrective Act', 'SÉCURITÉ', 'Actions remédier problèmes identifiés.', 'Actions addressing identified problems.'),
    (606, 'Audit conformité', 'Compliance', 'SÉCURITÉ', 'Vérification normes respect exigences.', 'Standards compliance requirements verification.'),
    (607, 'Accréditation', 'Accreditation', 'SÉCURITÉ', 'Reconnaissance officielle compétence externe.', 'Official recognition external competency proof.'),
    (608, 'Formation SST', 'SST Training', 'SÉCURITÉ', 'Programme santé sécurité travail.', 'Work health safety training program.'),
    (609, 'Habilitation', 'Qualification', 'SÉCURITÉ', 'Autorisation travail domaine spécialisé.', 'Specialized domain work authorization.'),
    (610, 'Document risque', 'Risk Doc', 'SÉCURITÉ', 'Affichage visible avertissement emploi.', 'Visible employment warning signage.'),
    (611, 'Equipe pompiers', 'Fire Brigade', 'SÉCURITÉ', 'Service intervention professionnels sapeurs.', 'Professional firefighter service intervention.'),
    (612, 'Équipe secours', 'Rescue Team', 'SÉCURITÉ', 'Sauvetage opérations extrication urgence.', 'Rescue operations extrication emergency team.'),
    (613, 'Police locale', 'Local Police', 'SÉCURITÉ', 'Autorités ordre sécurité maintien.', 'Order security maintenance authorities.'),
    (614, 'Gendarme prés', 'Gendarmes', 'SÉCURITÉ', 'Forces armées maintien ordre France.', 'Armed forces France order maintenance.'),
    (615, 'Sécurité privée', 'Private Sec', 'SÉCURITÉ', 'Entreprise prestataire surveillance.', 'Private surveillance contractor firm.'),
    (616, 'Vigile discrète', 'Discrete Guard', 'SÉCURITÉ', 'Brassard civil sans uniforme voyant.', 'Armband civilian unmarked subtle uniform.'),
    (617, 'Ronde surveillance', 'Patrol', 'SÉCURITÉ', 'Contrôle périodique zone régulier.', 'Periodic regular zone control patrol.'),
    (618, 'Caméra surveillance', 'CCTV', 'SÉCURITÉ', 'Enregistrement vidéo zone archivé.', 'Video recording zone archived footage.'),
    (619, 'Méga pixel 4K', 'Resolution', 'SÉCURITÉ', 'Définition image vidéo clarté.', 'Video image definition clarity resolution.'),
    (620, 'Cloud stockage', 'Video Store', 'SÉCURITÉ', 'Archivage distant sécurisé données.', 'Secure remote data archival storage.'),
    (621, 'Rétention vidéo', 'Retention', 'SÉCURITÉ', 'Durée conservation enregistrements légale.', 'Legal recording conservation duration retention.'),
    (622, 'Accès contrôlé', 'Access Log', 'SÉCURITÉ', 'Enregistrement entrées sorties personnel.', 'Personnel entry exit recording log.'),
    (623, 'Badge magnétique', 'Badge', 'SÉCURITÉ', 'Carte identification magnétique accès.', 'Magnetic identification card access.'),
    (624, 'Lecteur biométrique', 'Biometric', 'SÉCURITÉ', 'Empreinte doigt iris reconnaissance.', 'Fingerprint iris recognition technology.'),
    (625, 'Code PIN', 'PIN Code', 'SÉCURITÉ', 'Combinaison chiffre accès porte.', 'Numeric combination door access code.'),
    (626, 'Poste vigile', 'Guard Post', 'SÉCURITÉ', 'Station surveillance point focal centralisé.', 'Centralized surveillance station guard post.'),
    (627, 'Détecteur mouvement', 'Motion Sensor', 'SÉCURITÉ', 'Activation automatique présence intrusion.', 'Automatic activation presence intrusion detection.'),
    (628, 'Infrarouge passif', 'Passive IR', 'SÉCURITÉ', 'Technique détection chaleur corporelle.', 'Body heat detection technique technology.'),
    (629, 'Double technologie', 'Dual Tech', 'SÉCURITÉ', 'Combinés capteur confirmation fausse alarme.', 'Combined sensors false alarm confirmation.'),
    (630, 'Sirène externe', 'Siren', 'SÉCURITÉ', 'Alarme sonore audible visible.', 'Visible audio alarm siren system.'),
    (631, 'Boîte tamper', 'Tamper Box', 'SÉCURITÉ', 'Protection tentative sabotage équipement.', 'Sabotage attempt equipment protection.'),
    (632, 'Batterie secours', 'Backup Battery', 'SÉCURITÉ', 'Alimentation continue coupure secteur.', 'Continued power mains cutoff backup.'),
    (633, 'Redondance', 'Redundant', 'SÉCURITÉ', 'Système double secours basculement.', 'Backup system double failover switching.'),
    (634, 'Test mensuel', 'Monthly Test', 'SÉCURITÉ', 'Vérification régulière fonctionnement correct.', 'Regular correct operation functionality verification.'),
    (635, 'Logs événements', 'Event Log', 'SÉCURITÉ', 'Journal horodaté incidents alertes.', 'Timestamped incidents alerts journal log.'),
    (636, 'Analyse données', 'Data Review', 'SÉCURITÉ', 'Étude tendances statistiques sécurité.', 'Security statistics trends analysis study.'),
    (637, 'Rapport mensuel', 'Monthly Report', 'SÉCURITÉ', 'Synthèse incidents période mensuelle.', 'Monthly period incidents synthesis report.'),
    (638, 'Audit externe', 'External Audit', 'SÉCURITÉ', 'Évaluation indépendante conformité.', 'Compliance independent external evaluation.'),
    (639, 'Certification ISO', 'ISO Cert', 'SÉCURITÉ', 'Normes qualité management système.', 'System quality management norms standards.'),
    (640, 'Procédure incident', 'Procedure', 'SÉCURITÉ', 'Protocole réponse situation anormale.', 'Abnormal situation response protocol procedure.'),
    (641, 'Cellule crise', 'Crisis Cell', 'SÉCURITÉ', 'Équipe gestion urgence majeure.', 'Major emergency management team response.'),
    (642, 'Plan continuité', 'Continuity', 'SÉCURITÉ', 'Maintien services interruption minimale.', 'Service continuation minimal interruption plan.'),
    (643, 'Rôles responsabilités', 'Roles', 'SÉCURITÉ', 'Désignation autorités décision crise.', 'Crisis decision authority designation roles.'),
    (644, 'Communication', 'Comms', 'SÉCURITÉ', 'Canaux alertes notification personnel.', 'Personnel notification alerting communication channels.'),
    (645, 'Médias relations', 'Press', 'SÉCURITÉ', 'Gestion communication externe médias.', 'External media communication management press.'),
    (646, 'Porte-parole', 'Spokesman', 'SÉCURITÉ', 'Représentant autorisé déclarations officielles.', 'Official statements authorized representative spokesman.'),
    (647, 'Ligne info', 'Hotline', 'SÉCURITÉ', 'Téléphone information public assistance.', 'Public assistance information telephone hotline.'),
    (648, 'Réseaux sociaux', 'Social Media', 'SÉCURITÉ', 'Plateforme diffusion information transparence.', 'Information dissemination transparency platform.'),
    (649, 'Debriefing crise', 'Post-Crisis', 'SÉCURITÉ', 'Réunion analyse bilan gestion situation.', 'Situation management analysis meeting debrief.'),
    (650, 'Leçons apprises', 'Lessons', 'SÉCURITÉ', 'Recommandations améliorations futures gestion.', 'Future management improvements recommendations.'),
]

# BATCH 07: Booking & Management (IDs 651-750) - 100 terms
batch_07 = [
    (651, 'Artiste confirmé', 'Confirmed Artist', 'BOOKING', 'Contrat signé engagement ferme.', 'Signed contract firm commitment artist.'),
    (652, 'Option hold', 'Option Hold', 'BOOKING', 'Réservation provisoire confirmation attente.', 'Provisional reservation awaiting confirmation.'),
    (653, 'Pre-booking', 'Pre-Booking', 'BOOKING', 'Intérêt initial avant négociation.', 'Initial interest before negotiation stage.'),
    (654, 'Confirmation urgence', 'Rush Booking', 'BOOKING', 'Artiste dernière minute courts délais.', 'Last minute artist short notice booking.'),
    (655, 'Cancellation fee', 'Cancel Fee', 'BOOKING', 'Pénalité résiliation anticipée.', 'Early termination penalty cancellation charge.'),
    (656, 'Rain date', 'Alternate Date', 'BOOKING', 'Date alternative intempéries reports.', 'Bad weather rescheduled alternate date.'),
    (657, 'Hold harmless', 'Indemnify', 'BOOKING', 'Clause exonération responsabilité tiers.', 'Third-party liability exemption clause.'),
    (658, 'Right refusal', 'Right Refusal', 'BOOKING', 'Préemption engagement date retrait.', 'Engagement date withdrawal preemption right.'),
    (659, 'Counter offer', 'Counter', 'BOOKING', 'Contre-proposition modification conditions.', 'Conditions modification counter offer proposal.'),
    (660, 'Negotiation', 'Deal Talks', 'BOOKING', 'Discussion accords termes prix.', 'Price terms agreement discussion talks.'),
    (661, 'Non-exclusive', 'Non-Excl', 'BOOKING', 'Artiste peut date même période.', 'Artist can perform same period dates.'),
    (662, 'Exclusive window', 'Exclusive', 'BOOKING', 'Interdiction date fenêtre temporelle.', 'Temporary window date prohibition exclusive.'),
    (663, 'First dibs', 'First Option', 'BOOKING', 'Priorité information nouvelle date.', 'Priority new date information first option.'),
    (664, 'Right match', 'Match Right', 'BOOKING', 'Option égaler meilleure offre concurrence.', 'Better competing offer matching option right.'),
    (665, 'Matching clause', 'Match Clause', 'BOOKING', 'Condition égalisation offre supérieure.', 'Superior offer equalization condition clause.'),
    (666, 'Walk provision', 'Walk Clause', 'BOOKING', 'Droit résiliation sans cause majeure.', 'Termination right without major cause reason.'),
    (667, 'Out clause', 'Exit Clause', 'BOOKING', 'Possibilité dégagement contrat spécifique.', 'Specific contract disengagement exit possibility.'),
    (668, 'Termination rights', 'Term Rights', 'BOOKING', 'Conditions fin contrat résiliation.', 'Contract termination conditions end rights.'),
    (669, 'Material breach', 'Material Break', 'BOOKING', 'Violation violation contrat fondamentale.', 'Fundamental contract violation breach material.'),
    (670, 'Cure period', 'Cure Time', 'BOOKING', 'Délai récification conditions violation.', 'Violation condition rectification cure time period.'),
    (671, 'Liquidated damage', 'Liquidated Dmg', 'BOOKING', 'Compensation forfaitaire dommages prédéfinis.', 'Predefined damages compensation forfeited amount.'),
    (672, 'Performance bond', 'Perf Bond', 'BOOKING', 'Garantie exécution contrat dépôt.', 'Contract performance guarantee deposit bond.'),
    (673, 'Escrow', 'Escrow', 'BOOKING', 'Tiers holding montant paiement sécurisé.', 'Secured payment third-party holding amount.'),
    (674, 'Earnest money', 'Earnest', 'BOOKING', 'Acompte démonstration bonne foi engagement.', 'Good faith commitment earnest deposit payment.'),
    (675, 'Set list approval', 'Set Approval', 'BOOKING', 'Validation répertoire autorisation préalable.', 'Advanced authorization repertoire approval validation.'),
    (676, 'Sound requirements', 'Sound Spec', 'BOOKING', 'Besoins sono technique spécifications.', 'Technical sound specifications requirements needs.'),
    (677, 'Technical rider', 'Tech Rider', 'BOOKING', 'Document exigences technique équipement.', 'Equipment technique requirements document rider.'),
    (678, 'Crew rider', 'Crew Rider', 'BOOKING', 'Personnel structure accompagnement artiste.', 'Artist accompanying personnel structure rider.'),
    (679, 'Lighting cues', 'Light Cues', 'BOOKING', 'Points repère éclairage musique.', 'Music lighting reference points cues.'),
    (680, 'Video playback', 'Video Play', 'BOOKING', 'Bandes vidéo lecture séquencée.', 'Sequenced video tape playback bands.'),
    (681, 'Custom graphics', 'Custom Graph', 'BOOKING', 'Écrans vidéo logos personnalisés.', 'Customized logos video screens displays.'),
    (682, 'Merchandise rights', 'Merch Rights', 'BOOKING', 'Vente produits dérivés site.', 'On-site derivative product sales rights.'),
    (683, 'Door percentage', 'Door %', 'BOOKING', 'Pourcentage tickets revenus partage.', 'Ticket revenue splitsharing door percentage.'),
    (684, 'Guaranteed minimum', 'Guarantee', 'BOOKING', 'Montant minimum assuré avant dépenses.', 'Minimum amount assured before expenses.'),
    (685, 'Ticket revenue', 'Ticket Rev', 'BOOKING', 'Montants ventes billets collectés.', 'Collected ticket sales revenue amounts.'),
    (686, 'Concession sales', 'Concession', 'BOOKING', 'Ventes buvette nourriture bénéfices.', 'Food refreshment concession profits sales.'),
    (687, 'Secondary market', 'Secondary', 'BOOKING', 'Revente tickets marché résale.', 'Ticket resale secondary market reselling.'),
    (688, 'Comp tickets', 'Comps', 'BOOKING', 'Billets gratuits complimentaires presse.', 'Free complimentary press tickets comps.'),
    (689, 'VIP upgrade', 'VIP Upgrade', 'BOOKING', 'Amélioration places premium paiement.', 'Premium seating payment upgrade VIP.'),
    (690, 'Box seat', 'Box Seat', 'BOOKING', 'Loge privée places réservées.', 'VIP private box reserved seating area.'),
    (691, 'Pit access', 'Pit Pass', 'BOOKING', 'Accès fosse photographes media.', 'Photographer media fosse pit access.'),
    (692, 'Soundcheck pass', 'Soundcheck', 'BOOKING', 'Accès essai son avant spectacle.', 'Pre-show sound check access pass.'),
    (693, 'Meet greet', 'Meet Greet', 'BOOKING', 'Rencontre artiste fans après.', 'Post-show artist fan meeting greet.'),
    (694, 'Photo opportunity', 'Photo Op', 'BOOKING', 'Séance photo souvenir fans.', 'Fan souvenir photo opportunity session.'),
    (695, 'Autograph session', 'Autograph', 'BOOKING', 'Dédicace articles signatures.', 'Item signature autograph signing session.'),
    (696, 'VIP lounge', 'Lounge', 'BOOKING', 'Espace client privé confortable.', 'Comfortable private client lounge area.'),
    (697, 'Hospitality', 'Hospitality', 'BOOKING', 'Accueil personnalisé services premium.', 'Premium services personalized welcome hospitality.'),
    (698, 'Catering package', 'Cater Pack', 'BOOKING', 'Formule restauration clients offerte.', 'Offered client food package catering.'),
    (699, 'Open bar', 'Open Bar', 'BOOKING', 'Boissons consommation gratuite illimitée.', 'Unlimited free beverage consumption bar.'),
    (700, 'Premium menu', 'Premium Menu', 'BOOKING', 'Sélection gastronomie haute cuisine.', 'Haute cuisine selection gourmet premium.'),
    (701, 'Sommelier', 'Sommelier', 'BOOKING', 'Expert vin accords mets-vins.', 'Wine pairing expert sommelier wine pairing.'),
    (702, 'Mixologist', 'Mixologist', 'BOOKING', 'Préparation cocktails création personnalisée.', 'Personalized cocktail creation mixologist preparation.'),
    (703, 'Event coordinator', 'Coordinator', 'BOOKING', 'Gestionnaire logistique global planning.', 'Overall logistical planner coordinator manager.'),
    (704, 'Project manager', 'PM', 'BOOKING', 'Pilote équipe suivi timeline.', 'Timeline tracking team pilot project.'),
    (705, 'Producer', 'Producer', 'BOOKING', 'Responsable créative spectacle global.', 'Overall creative show responsibility producer.'),
    (706, 'Director', 'Director', 'BOOKING', 'Chef vision artistique exécution.', 'Artistic vision execution leader chief director.'),
    (707, 'Assistant director', 'Asst Dir', 'BOOKING', 'Support réalisation coordination terrain.', 'On-site coordination realization assistant support.'),
    (708, 'Production assistant', 'PA', 'BOOKING', 'Assistance générale polyvalent soutien.', 'General support multitasking assistance PA.'),
    (709, 'Runners', 'Runners', 'BOOKING', 'Personnel courses petites tâches support.', 'Support small task running personnel runners.'),
    (710, 'Runners brief', 'Runner Brief', 'BOOKING', 'Briefing instructions directives coureurs.', 'Runner directives instructions briefing instructions.'),
    (711, 'Contingency staff', 'Contingency', 'BOOKING', 'Personnel réserve remplacement urgence.', 'Emergency replacement contingency personnel reserve.'),
    (712, 'Staff allocation', 'Allocation', 'BOOKING', 'Distribution ressources personnel zones.', 'Zone personnel resources distribution allocation.'),
    (713, 'Coverage ratio', 'Ratio', 'BOOKING', 'Proportion encadrement public sécurité.', 'Public security supervision coverage ratio.'),
    (714, 'Shift scheduling', 'Shifts', 'BOOKING', 'Horaires rotation personnel équipes.', 'Personnel team rotation scheduling shifts.'),
    (715, 'Break rotation', 'Break Schedule', 'BOOKING', 'Pauses repos étalées rotation.', 'Staggered rotation rest breaks schedule.'),
    (716, 'Meal ticket', 'Meal Ticket', 'BOOKING', 'Bon repas équipe restauration.', 'Team meal voucher restauration ticket.'),
    (717, 'Staff meals', 'Staff Meals', 'BOOKING', 'Nourriture personnel équipes restau.', 'Team food personnel restaurant meals.'),
    (718, 'Overtime', 'Overtime', 'BOOKING', 'Heures supplémentaires surpaiement.', 'Extra hours overpayment overtime premium.'),
    (719, 'Per diem', 'Per Diem', 'BOOKING', 'Allocation indemnité journalière.', 'Daily allowance indemnity per diem.'),
    (720, 'Travel allowance', 'Travel', 'BOOKING', 'Remboursement transport déplacements.', 'Travel expense reimbursement allowance.'),
    (721, 'Accommodation', 'Hotel', 'BOOKING', 'Hébergement logement fourni personnel.', 'Personnel lodging accommodation provided.'),
    (722, 'Group rate', 'Group Rate', 'BOOKING', 'Tarif réduit groupe volume.', 'Volume group discount rate tariff.'),
    (723, 'Booking confirmation', 'Confirmation', 'BOOKING', 'Validation définitive engagement confirmé.', 'Final engagement validation confirmed booking.'),
    (724, 'Purchase order', 'PO', 'BOOKING', 'Commande officielle fournitures services.', 'Official supply services order PO.'),
    (725, 'Work order', 'Work Order', 'BOOKING', 'Instruction exécution tâches spécifiques.', 'Specific task execution instruction order.'),
    (726, 'Schedule adherence', 'Schedule', 'BOOKING', 'Respect calendrier planning timeline.', 'Timeline planning calendar adherence respect.'),
    (727, 'Milestones', 'Milestones', 'BOOKING', 'Points étapes majeurs progression réalisation.', 'Major realization progress stage points.'),
    (728, 'Deliverables', 'Deliverables', 'BOOKING', 'Livrables productions attendues résultats.', 'Expected production results deliverables.'),
    (729, 'Quality assurance', 'QA', 'BOOKING', 'Vérification normes qualité conformité.', 'Compliance quality standards verification QA.'),
    (730, 'Final sign-off', 'Sign-off', 'BOOKING', 'Approbation complétude validation finale.', 'Final validation completion approval sign-off.'),
    (731, 'Acceptance', 'Acceptance', 'BOOKING', 'Réception satisfaction client acception.', 'Customer satisfaction receipt acceptance.'),
    (732, 'Payment terms', 'Payment Terms', 'BOOKING', 'Calendrier paiements versements conditions.', 'Payment schedule conditions calendar.'),
    (733, 'Invoice cycle', 'Invoice Cycle', 'BOOKING', 'Fréquence facturation mensuelle trimestrielle.', 'Quarterly monthly billing invoice frequency.'),
    (734, 'Late payment', 'Late Fee', 'BOOKING', 'Pénalité retard paiement dépassement.', 'Overage delayed payment penalty fee.'),
    (735, 'Discount early', 'Early Discount', 'BOOKING', 'Réduction avance paiement anticipé.', 'Advance payment early payment discount.'),
    (736, 'Volume discount', 'Volume Disc', 'BOOKING', 'Réduction quantité engagement volume.', 'Volume commitment quantity discount reduction.'),
    (737, 'Seasonal pricing', 'Seasonal', 'BOOKING', 'Tarif variations haute basse saison.', 'High low season tariff pricing variations.'),
    (738, 'Dynamic pricing', 'Dynamic', 'BOOKING', 'Prix adaptation demande réelle flexible.', 'Flexible real demand price adaptation.'),
    (739, 'Package deal', 'Package', 'BOOKING', 'Proposition combiné économies forfait.', 'Bundled savings proposition forfeited deal.'),
    (740, 'Cross-sell', 'Cross-sell', 'BOOKING', 'Vente additionnelle services complémentaires.', 'Complementary services additional selling cross-sell.'),
    (741, 'Upsell', 'Upsell', 'BOOKING', 'Promotion upgrade premium supérieur.', 'Superior premium upgrade promotion upsell.'),
    (742, 'Retention rate', 'Retention', 'BOOKING', 'Pourcentage client fidélité renouvellement.', 'Client loyalty renewal percentage rate.'),
    (743, 'Churn rate', 'Churn', 'BOOKING', 'Pourcentage client perte cessation.', 'Client loss cessation percentage churn rate.'),
    (744, 'Customer lifetime', 'CLV', 'BOOKING', 'Valeur totale client relation durée.', 'Relationship duration client total value.'),
    (745, 'ROI', 'ROI', 'BOOKING', 'Retour investissement rentabilité profit.', 'Profit rentability investment return ROI.'),
    (746, 'Break even', 'Break Even', 'BOOKING', 'Seuil rentabilité profits couverture.', 'Profit coverage breakeven threshold.'),
    (747, 'Profit margin', 'Margin', 'BOOKING', 'Bénéfice net pourcentage revenu.', 'Revenue percentage net profit margin.'),
    (748, 'Cost center', 'Cost Center', 'BOOKING', 'Centre imputations budget dépenses.', 'Expense budget allocation cost center.'),
    (749, 'Revenue stream', 'Revenue', 'BOOKING', 'Source sources revenu principal secondaire.', 'Secondary primary source revenue stream.'),
    (750, 'Budget variance', 'Variance', 'BOOKING', 'Écart budget prévision réalité.', 'Budget forecast reality variance gap.'),
]

# BATCH 08: Juridique (IDs 751-850) - 100 terms
batch_08 = [
    (751, 'Accord cadre', 'Framework Agr', 'JURIDIQUE', 'Contrat général conditions standards.', 'General contract standard conditions agreement.'),
    (752, 'Clauses supplémentaires', 'Amendments', 'JURIDIQUE', 'Adjonction conditions modification contrat.', 'Contract conditions modification additions amendments.'),
    (753, 'Droit applicable', 'Governing Law', 'JURIDIQUE', 'Loi juridiction compétente contrat.', 'Contract jurisdiction legal governing law.'),
    (754, 'Élection domicile', 'Jurisdiction', 'JURIDIQUE', 'Lieu procédure tribunal compétent.', 'Tribunal venue jurisdiction procedure location.'),
    (755, 'Arbitrage', 'Arbitration', 'JURIDIQUE', 'Tiers décideur résolution confidentialité.', 'Confidential resolution tiers arbitrator decision.'),
    (756, 'Médiation', 'Mediation', 'JURIDIQUE', 'Tiers facilitateur accord négociation.', 'Negotiation agreement facilitator tiers mediation.'),
    (757, 'Litige', 'Litigation', 'JURIDIQUE', 'Procédure procès affrontement judiciaire.', 'Judicial proceeding court litigation lawsuit process.'),
    (758, 'Dommages intérêts', 'Damages', 'JURIDIQUE', 'Compensation réparation perte subie.', 'Loss repair compensation damages suffered.'),
    (759, 'Dommages exemplaires', 'Punitive', 'JURIDIQUE', 'Réparation supérieure dommage punitif.', 'Punitive damage excessive repair above.'),
    (760, 'Attribution faute', 'Fault', 'JURIDIQUE', 'Responsabilité établissement tiers culpabilité.', 'Third-party guilt liability establishment fault.'),
    (761, 'Causalité', 'Causation', 'JURIDIQUE', 'Lien direct cause événement dommage.', 'Damage event direct cause link.'),
    (762, 'Préjudice moral', 'Moral Dmg', 'JURIDIQUE', 'Souffrance psychologique atteinte honneur.', 'Honor injury psychological suffering damage.'),
    (763, 'Préjudice esthétique', 'Aesthetics', 'JURIDIQUE', 'Corps figuration image apparence.', 'Appearance image body figuration damage.'),
    (764, 'Perte de chance', 'Lost Chance', 'JURIDIQUE', 'Privation opportunité obtention profit.', 'Profit opportunity loss privation chance.'),
    (765, 'Bénéfice manqué', 'Lost Profits', 'JURIDIQUE', 'Réductions gains escomptés attendus.', 'Expected profits expected gains reduction.'),
    (766, 'Lucrum cessans', 'Lost Income', 'JURIDIQUE', 'Revenu cesse perte cessation activité.', 'Activity ceased revenue loss cessation.'),
    (767, 'Damnum emergens', 'Direct Loss', 'JURIDIQUE', 'Perte subie immediate dépense.', 'Immediate suffered loss expense direct.'),
    (768, 'Culpa in contrahendo', 'Pre-Cont', 'JURIDIQUE', 'Faute signature négociation contrat.', 'Contract signature negotiation fault faute.'),
    (769, 'Culpa in re ipsa', 'Strict Liability', 'JURIDIQUE', 'Responsabilité automatique sans culpa.', 'Automatic no-fault responsibility liability.'),
    (770, 'Vis maior', 'Acts of God', 'JURIDIQUE', 'Force nature imprévue assistance.', 'Unforeseen nature force assistance.'),
    (771, 'Cas fortuit', 'Accident', 'JURIDIQUE', 'Événement imprévisible inévitable survenu.', 'Unforeseen unavoidable occurrence event.'),
    (772, 'Détournement responsabilité', 'Immunity', 'JURIDIQUE', 'Exception immunité exonération obligation.', 'Obligation exoneration exception immunity.'),
    (773, 'Limitation responsabilité', 'Cap Liability', 'JURIDIQUE', 'Plafond montant maximum responsabilité.', 'Maximum responsibility ceiling amount cap.'),
    (774, 'Exonération totale', 'Full Waiver', 'JURIDIQUE', 'Abandon total droit revendication.', 'Total claim right abandonment waiver.'),
    (775, 'Subrogation', 'Subrogation', 'JURIDIQUE', 'Remplacement droits tiers assureur.', 'Insurer third-party rights replacement.'),
    (776, 'Cession droits', 'Assignment', 'JURIDIQUE', 'Transfert obligation créance tiers.', 'Third-party claim obligation transfer.'),
    (777, 'Séquestre', 'Escrow', 'JURIDIQUE', 'Dépôt tiers mains tierces sécurisé.', 'Secured third-part hands deposit escrow.'),
    (778, 'Saisie conservatoire', 'Attachment', 'JURIDIQUE', 'Mesure prévention seizure actif.', 'Asset seizure prevention measure attachment.'),
    (779, 'Hypothèque', 'Mortgage', 'JURIDIQUE', 'Garantie prêt biens immobiliers.', 'Real estate property loan guarantee.'),
    (780, 'Gage', 'Pledge', 'JURIDIQUE', 'Garantie mobilier prêt immédiate.', 'Immediate loan movable property guarantee.'),
    (781, 'Nantissement', 'Collateral', 'JURIDIQUE', 'Sûreté bien meuble prêteur.', 'Movable property lender security.'),
    (782, 'Créancier', 'Creditor', 'JURIDIQUE', 'Crédit prêteur actif dû.', 'Debt creditor owed asset lender.'),
    (783, 'Débiteur', 'Debtor', 'JURIDIQUE', 'Obligé paiement dû passif.', 'Payment obligation owed debtor liability.'),
    (784, 'Insolvabilité', 'Insolvency', 'JURIDIQUE', 'Impossibilité paiement dettes passif.', 'Debt payment impossibility insolvency liability.'),
    (785, 'Faillite', 'Bankruptcy', 'JURIDIQUE', 'Procédure insolvabilité liquidation actif.', 'Asset liquidation insolvency bankruptcy procedure.'),
    (786, 'Redressement', 'Restructuring', 'JURIDIQUE', 'Période continuation activité restructuration.', 'Ongoing activity restructuring continuation period.'),
    (787, 'Plan homologué', 'Confirmed Plan', 'JURIDIQUE', 'Accord créanciers reprise activité.', 'Creditor agreement activity restart plan.'),
    (788, 'Moratoire', 'Moratorium', 'JURIDIQUE', 'Suspension paiement délai respiration.', 'Payment suspension respiration delay moratorium.'),
    (789, 'Grâce délai', 'Grace Period', 'JURIDIQUE', 'Ajournement paiement terme extension.', 'Payment term extension postponement grace period.'),
    (790, 'Intérêts', 'Interest', 'JURIDIQUE', 'Rémunération taux prêt annuel.', 'Annual loan rate compensation interest.'),
    (791, 'Pénalités', 'Penalties', 'JURIDIQUE', 'Sanction retard contrat infraction.', 'Infraction contract delay penalty sanctions.'),
    (792, 'Indemnités', 'Allowances', 'JURIDIQUE', 'Compensations dédommagement réparation.', 'Repair compensation allowances indemnities.'),
    (793, 'Précompte', 'Withholding', 'JURIDIQUE', 'Prélèvement imposition source source.', 'Source tax withholding income deduction.'),
    (794, 'Retenue fiscale', 'Tax Withhold', 'JURIDIQUE', 'Prélèvement fiscal impôt proportionnel.', 'Proportional tax income withholding fiscal.'),
    (795, 'TVA', 'VAT', 'JURIDIQUE', 'Taxe valeur ajoutée pourcentage.', 'Added value percentage tax VAT.'),
    (796, 'Franchise TVA', 'VAT Free', 'JURIDIQUE', 'Exemption taxe micro-entreprise seuil.', 'Threshold micro-business exemption VAT.'),
    (797, 'Cotisations sociales', 'Social Charges', 'JURIDIQUE', 'Prélèvements sécurité santé retraite.', 'Retirement health security contributions social.'),
    (798, 'Déclaration impôt', 'Tax Return', 'JURIDIQUE', 'Formulaire revenu montants imposables.', 'Taxable amounts form tax return income.'),
    (799, 'Audit fiscal', 'Tax Audit', 'JURIDIQUE', 'Vérification fisc impôt comptabilité.', 'Accounting tax verification audit fisc.'),
    (800, 'Redressement fiscal', 'Tax Adjustment', 'JURIDIQUE', 'Correction différence impôt manquant.', 'Missing tax difference correction.'),
    (801, 'Contentieux fiscal', 'Tax Dispute', 'JURIDIQUE', 'Litige trésor réclamation contentieux.', 'Treasury dispute contention claim dispute.'),
    (802, 'Transaction', 'Settlement', 'JURIDIQUE', 'Accord résolution différend transaction.', 'Dispute resolution agreement settlement.'),
    (803, 'Reconnaissance', 'Admission', 'JURIDIQUE', 'Acceptation reconnu culpabilité tiers.', 'Third-party guilt accepted admission.'),
    (804, 'Désistement', 'Withdrawal', 'JURIDIQUE', 'Abandon droit revendication plainte.', 'Complaint claim right abandonment withdrawal.'),
    (805, 'Appel', 'Appeal', 'JURIDIQUE', 'Recours jugement niveau supérieur.', 'Higher level judgment recourse appeal.'),
    (806, 'Cassation', 'Supreme Rech', 'JURIDIQUE', 'Recours ultime annulation jugement.', 'Ultimate judgment annulment recourse cassation.'),
    (807, 'Pourvoi', 'Petition', 'JURIDIQUE', 'Demande ultime réexamen cour.', 'Court reexamination ultimate demands petition.'),
    (808, 'Délai de prescription', 'Limitation', 'JURIDIQUE', 'Terme action légale temporelle limite.', 'Temporal legal action term limitations.'),
    (809, 'Interruption prescription', 'Suspend', 'JURIDIQUE', 'Arrêt délai cause reconnaissance admission.', 'Admission cause delay stop suspension.'),
    (810, 'Renonciation', 'Waiver', 'JURIDIQUE', 'Abandon droit non-recours tiers.', 'Third-party abandonment non-action waiver.'),
    (811, 'Compensation créances', 'Offset', 'JURIDIQUE', 'Annulation mutuelles dettes droit.', 'Right mutual debt cancellation offset.'),
    (812, 'Novation', 'Renewal', 'JURIDIQUE', 'Remplacement obligation nouvelle contrat.', 'New contract obligation replacement renewal.'),
    (813, 'Confusion', 'Merger', 'JURIDIQUE', 'Coalescence créancier débiteur annulation.', 'Debtor creditor coalescence annulation merger.'),
    (814, 'Remise dette', 'Forgiveness', 'JURIDIQUE', 'Pardon gracieux créancier abandon créance.', 'Gracious creditor abandonment debt forgiven.'),
    (815, 'Imprescriptibilité', 'Non-Barred', 'JURIDIQUE', 'Action pas prescription délai illimitée.', 'Unlimited action delay non-barred action.'),
    (816, 'Caractère personnel', 'Personal', 'JURIDIQUE', 'Contrat intuitu personae attachement.', 'Contract attachment personalae intuitu attachment.'),
    (817, 'Solidarité', 'Joint Liability', 'JURIDIQUE', 'Responsabilité conjointe solidaire ensemble.', 'Together joint together solidaire liability.'),
    (818, 'Principal', 'Principal', 'JURIDIQUE', 'Obligé fondamental responsable principal.', 'Responsible fundamental principal obligor party.'),
    (819, 'Caution', 'Guarantor', 'JURIDIQUE', 'Garant tiers obligation secondaire.', 'Secondary obligation third-party guarantor party.'),
    (820, 'Caution simple', 'Simple Guar', 'JURIDIQUE', 'Garantie débiteur principal exception.', 'Principal debtor guarantee simple exception.'),
    (821, 'Caution solidaire', 'Joint Guar', 'JURIDIQUE', 'Garantie personnelle responsable conjointe.', 'Joint responsible personal guarantee joint guar.'),
    (822, 'Recours caution', 'Recourse', 'JURIDIQUE', 'Droit poursuite principaux tiers.', 'Principal parties third-party pursuit recourse right.'),
    (823, 'Délégation', 'Delegation', 'JURIDIQUE', 'Transmission pouvoirs représentant mandataire.', 'Delegate power transmission representative.'),
    (824, 'Procuration', 'Power Attorney', 'JURIDIQUE', 'Pouvoirs restreints actes donnés.', 'Given acts restricted power attorney.'),
    (825, 'Mandat', 'Authority', 'JURIDIQUE', 'Représentation acte tiers mandat.', 'Third-party act representation mandate authority.'),
    (826, 'Acceptation', 'Acceptance', 'JURIDIQUE', 'Accord conditions offre contrat.', 'Offer conditions agreement acceptance contract.'),
    (827, 'Contre-offre', 'Counter', 'JURIDIQUE', 'Modification conditions nouvelle proposition.', 'New proposition conditions modification counter.'),
    (828, 'Consentement', 'Consent', 'JURIDIQUE', 'Accord libre volontaire parties.', 'Free voluntary agreement parties consent.'),
    (829, 'Vice consentement', 'Vitiating', 'JURIDIQUE', 'Dol erreur violence force majeure.', 'Force violence error fraud majeure error.'),
    (830, 'Dol', 'Fraud', 'JURIDIQUE', 'Manoeuvre tromper intention malhonnête.', 'Dishonest intention maneuvering fraud deception.'),
    (831, 'Erreur substance', 'Mistake', 'JURIDIQUE', 'Méconnaissance essentielle éléments contrat.', 'Essential contract elements misunderstanding mistake.'),
    (832, 'Violence contrat', 'Duress', 'JURIDIQUE', 'Contrainte menace consentement viole.', 'Threatened constraint consent violated duress.'),
    (833, 'Ordre loi public', 'Public Policy', 'JURIDIQUE', 'Sécurité ordre moralité société.', 'Society morality order security policy.'),
    (834, 'Clause pénale', 'Penalty Clause', 'JURIDIQUE', 'Sanction paiement infraction contrat.', 'Infraction contract payment penalty sanction.'),
    (835, 'Clause résolutoire', 'Resolution', 'JURIDIQUE', 'Annulation autorisée défaillance condition.', 'Condition failure cancellation authorized clause.'),
    (836, 'Clause suspensive', 'Suspensive', 'JURIDIQUE', 'Attente condition avant effectivité.', 'Before effectiveness condition waiting provision.'),
    (837, 'Clause compromissoire', 'Arbitration', 'JURIDIQUE', 'Engagement arbitrage résolution litige.', 'Litigation resolution arbitration engagement clause.'),
    (838, 'Droits d\'auteur', 'Copyright', 'JURIDIQUE', 'Protection oeuvre création immeuble.', 'Creator work protection property copyright.'),
    (839, 'Marque', 'Trademark', 'JURIDIQUE', 'Signe distinctif propriété commerciale.', 'Commercial property distinctive sign trademark.'),
    (840, 'Brevet', 'Patent', 'JURIDIQUE', 'Invention exclusivité droits temporaire.', 'Exclusive temporary innovation rights patent.'),
    (841, 'Secret commercial', 'Trade Sec', 'JURIDIQUE', 'Information confidentielle formule propriété.', 'Property formula confidential information trade.'),
    (842, 'Contrefaçon', 'Infringement', 'JURIDIQUE', 'Violation droits reproduction unauthorized.', 'Unauthorized reproduction rights violation infringe.'),
    (843, 'Piratage', 'Piracy', 'JURIDIQUE', 'Reproduction illégale diffusion non-autorisée.', 'Illegal reproduction unauthorized diffusion piracy.'),
    (844, 'Licence logiciel', 'Software Lic', 'JURIDIQUE', 'Autorisation usage limité conditions.', 'Limited conditions usage authorization license.'),
    (845, 'Clause EULA', 'EULA Clause', 'JURIDIQUE', 'Conditions utilisation logiciel acceptation.', 'Software usage conditions acceptance clause.'),
    (846, 'Propriété intellectuelle', 'IP', 'JURIDIQUE', 'Droits immatériels création originale.', 'Original creativity immaterial creation rights.'),
    (847, 'Cession IP', 'IP Transfer', 'JURIDIQUE', 'Transfert droits propriété tiers.', 'Third-party property rights transfer cession.'),
    (848, 'Mise en oeuvre', 'Implementation', 'JURIDIQUE', 'Application effective obligation clauses contrat.', 'Contract clauses obligations effective application.'),
    (849, 'Performance', 'Performance', 'JURIDIQUE', 'Exécution complète termes contractuels.', 'Complete contractual terms execution performance.'),
    (850, 'Fermeture contrat', 'Closure', 'JURIDIQUE', 'Fin obligations finition dernières.',' Final obligations last finishing closure.'),
]

# BATCH 09: Digital & IT (IDs 851-950) - 100 terms
batch_09 = [
    (851, 'Infrastructure cloud', 'Cloud Infra', 'DIGITAL', 'Serveurs distribués virtuels conteneur.', 'Virtualized distributed container servers.'),
    (852, 'SaaS plateforme', 'SaaS', 'DIGITAL', 'Logiciel abonnement cloud accès.', 'Cloud software subscription access SaaS.'),
    (853, 'PaaS développement', 'PaaS', 'DIGITAL', 'Plateforme développement application outils.', 'Application development platform tools PaaS.'),
    (854, 'IaaS infrastructure', 'IaaS', 'DIGITAL', 'Serveurs location infrastructure virtuelle.', 'Virtual infrastructure servers rental IaaS.'),
    (855, 'Conteneurisation', 'Containerization', 'DIGITAL', 'Emballage application isolation indépendante.', 'Application packaging isolation containerization.'),
    (856, 'Docker', 'Docker', 'DIGITAL', 'Plateforme conteneurs orchestration devops.', 'Devops orchestration containers platform docker.'),
    (857, 'Kubernetes', 'Kubernetes', 'DIGITAL', 'Orchestration conteneurs déploiement gestion.', 'Deployment management containers orchestration k8s.'),
    (858, 'Microservices', 'Microservices', 'DIGITAL', 'Architecture logiciel petit module.', 'Small module software architecture microservices.'),
    (859, 'API interfacing', 'API', 'DIGITAL', 'Interface programmation échange données.', 'Data exchange programming interface API.'),
    (860, 'REST protocole', 'REST', 'DIGITAL', 'Architecture stateless transfert requête.', 'Request transfer stateless web architecture.'),
    (861, 'GraphQL query', 'GraphQL', 'DIGITAL', 'Langage requête données flexible.', 'Flexible data query language GraphQL.'),
    (862, 'WebSocket temps', 'WebSocket', 'DIGITAL', 'Communication bidirectionnelle persistent.', 'Persistent bidirectional communication websocket.'),
    (863, 'MQTT protocole', 'MQTT', 'DIGITAL', 'Publish souscription IoT léger.', 'IoT lightweight publish subscribe protocol MQTT.'),
    (864, 'JSON format', 'JSON', 'DIGITAL', 'Échange données format texte.', 'Text format data exchange JSON.'),
    (865, 'XML structuration', 'XML', 'DIGITAL', 'Balisage hiérarchique données structurées.', 'Hierarchical markup structured data XML.'),
    (866, 'YAML config', 'YAML', 'DIGITAL', 'Configuration format lisible machine.', 'Machine readable configuration format YAML.'),
    (867, 'SQL base données', 'SQL', 'DIGITAL', 'Langage requête systèmes relation.', 'Relational systems query language SQL.'),
    (868, 'NoSQL non-relation', 'NoSQL', 'DIGITAL', 'Base données flexible non-structurée.', 'Flexible unstructured database NoSQL.'),
    (869, 'MongoDB document', 'MongoDB', 'DIGITAL', 'Base NoSQL document JSON collections.', 'JSON collections document NoSQL database.'),
    (870, 'Redis cache', 'Redis', 'DIGITAL', 'Cache mémoire clé-valeur performance.', 'Key-value memory cache performance redis.'),
    (871, 'ElasticSearch', 'Elasticsearch', 'DIGITAL', 'Moteur recherche texte intégral.', 'Full text search engine elasticsearch.'),
    (872, 'Index performance', 'Indexing', 'DIGITAL', 'Structure accélération recherche requête.', 'Query search acceleration structure index.'),
    (873, 'Sharding distribution', 'Sharding', 'DIGITAL', 'Distribution données horizontale réplication.', 'Horizontal data replication distribution sharding.'),
    (874, 'Replication', 'Replication', 'DIGITAL', 'Copie données plusieurs serveurs.', 'Multiple servers data copy replication.'),
    (875, 'Backup', 'Backup', 'DIGITAL', 'Sauvegarde données copies protection.', 'Data copies protection backup restoration.'),
    (876, 'Disaster recovery', 'DR', 'DIGITAL', 'Plan récupération catastrophe sinistre.', 'Disaster recovery catastrophe plan sinistre.'),
    (877, 'RTO', 'RTO', 'DIGITAL', 'Objectif temps récupération maximum.', 'Time recovery objective maximum RTO.'),
    (878, 'RPO', 'RPO', 'DIGITAL', 'Perte données maximum tolérable.', 'Maximum tolerable data loss RPO.'),
    (879, 'Haute disponibilité', 'HA', 'DIGITAL', 'Continuité service défaillance basculement.', 'Service continuation failover HA availability.'),
    (880, 'Load balancing', 'Load Balance', 'DIGITAL', 'Distribution charge trafic serveurs.', 'Servers traffic charge distribution balance.'),
    (881, 'Autoscaling', 'Autoscale', 'DIGITAL', 'Ajustement automatique ressources charge.', 'Automatic charge resources adjustment scaling.'),
    (882, 'CDN distribution', 'CDN', 'DIGITAL', 'Réseau distribution contenu local.', 'Local content distribution network CDN.'),
    (883, 'Cache layer', 'Cache', 'DIGITAL', 'Couche mémoire intermédiaire accès.', 'Intermediate memory layer access cache.'),
    (884, 'Rate limiting', 'Rate Limit', 'DIGITAL', 'Limitation requêtes par secondes quota.', 'Per second quota requests limitation rate.'),
    (885, 'Circuit breaker', 'Circuit Break', 'DIGITAL', 'Interruption automatique défaillance cascade.', 'Automatic interruption cascade failure circuit.'),
    (886, 'Retry strategy', 'Retry', 'DIGITAL', 'Tentative réessai délai exponentielle.', 'Exponential delay retry attempt strategy.'),
    (887, 'Timeout', 'Timeout', 'DIGITAL', 'Délai maximum réponse secondes.', 'Maximum response delay seconds timeout.'),
    (888, 'Logging', 'Logging', 'DIGITAL', 'Enregistrement événements audit traces.', 'Audit traces events recording logging.'),
    (889, 'Monitoring', 'Monitoring', 'DIGITAL', 'Surveillance métriques système alertes.', 'System metrics surveillance alerts monitoring.'),
    (890, 'Alerting', 'Alerting', 'DIGITAL', 'Notification anomalies seuils dépassés.', 'Threshold exceeded anomalies notifications.'),
    (891, 'Métriques prometheus', 'Prometheus', 'DIGITAL', 'Outil collecte exposé exposé métriques.', 'Metrics collection exposition tool prometheus.'),
    (892, 'Visualisation grafana', 'Grafana', 'DIGITAL', 'Dashboards graphiques visualisation données.', 'Data visualization graphs dashboards grafana.'),
    (893, 'Tracing distribué', 'Tracing', 'DIGITAL', 'Suivi requête travers services.', 'Service across request tracking tracing.'),
    (894, 'APM application', 'APM', 'DIGITAL', 'Surveillance performance application produit.', 'Production application performance surveillance APM.'),
    (895, 'ELK stack', 'ELK', 'DIGITAL', 'Elasticsearch logstash kibana suite.', 'Kibana logstash elasticsearch stack suite.'),
    (896, 'Splunk', 'Splunk', 'DIGITAL', 'Plateforme données visualisation analyse.', 'Analysis visualization platform data splunk.'),
    (897, 'DataDog', 'DataDog', 'DIGITAL', 'Observabilité cloud monitoring infrastructure.', 'Infrastructure monitoring cloud observability.'),
    (898, 'New Relic', 'New Relic', 'DIGITAL', 'Performance application SAAS surveillance.', 'Surveillance SAAS application performance.'),
    (899, 'DevOps.culture', 'DevOps', 'DIGITAL', 'Intégration développement opérations collaboration.', 'Operations development collaboration integration culture.'),
    (900, 'CI/CD pipeline', 'CI/CD', 'DIGITAL', 'Intégration continue déploiement automatisé.', 'Automated deployment continuous integration.'),
    (901, 'Jenkins automatisation', 'Jenkins', 'DIGITAL', 'Serveur intégration continue orchestration.', 'Orchestration continuous integration server.'),
    (902, 'Git version', 'Git', 'DIGITAL', 'Système contrôle version décentralisé.', 'Distributed version control system git.'),
    (903, 'GitHub collaborative', 'GitHub', 'DIGITAL', 'Plateforme Git collaboration sociale.', 'Social collaboration platform git github.'),
    (904, 'GitLab self-hosted', 'GitLab', 'DIGITAL', 'Alternative GitHub infrastructure branche.', 'Branch infrastructure alternative gitlab.'),
    (905, 'Pull request review', 'PR', 'DIGITAL', 'Demande fusion code révision pairs.', 'Peer review code fusion request pull.'),
    (906, 'Code review', 'Code Review', 'DIGITAL', 'Inspection code pairs qualité gestion.', 'Management quality pairs code inspection.'),
    (907, 'Static analysis', 'Static Anal', 'DIGITAL', 'Analyse code sans exécution bugs.', 'Bugs execution without code analysis static.'),
    (908, 'Linting', 'Linting', 'DIGITAL', 'Vérification style code conformité règles.', 'Rules conformity style code verification.'),
    (909, 'Testing unitaire', 'Unit Test', 'DIGITAL', 'Test composant isolé validation.', 'Validation isolated component test unit.'),
    (910, 'Testing intégration', 'Integration', 'DIGITAL', 'Test composants ensemble interaction.', 'Interaction together components test integration.'),
    (911, 'Testing acceptation', 'Acceptance', 'DIGITAL', 'Test besoin utilisateur acceptation.', 'Acceptance user need test acceptance.'),
    (912, 'Testing performance', 'Performance', 'DIGITAL', 'Test charge vitesse stress test.', 'Stress test speed charge performance test.'),
    (913, 'Testing sécurité', 'Security Test', 'DIGITAL', 'Test vulnérabilité pénétration attaque.', 'Attack penetration vulnerability test security.'),
    (914, 'Code coverage', 'Coverage', 'DIGITAL', 'Couverture code testée pourcentage.', 'Tested percentage code coverage lines.'),
    (915, 'Regression suite', 'Regression', 'DIGITAL', 'Test automatisé absence régression.', 'Regression non-occurence automated test suite.'),
    (916, 'Documentation', 'Docs', 'DIGITAL', 'Écriture guides manuels références.', 'References manual guides writing documentation.'),
    (917, 'README', 'README', 'DIGITAL', 'Fichier introduction projet installation.', 'Installation project introduction file readme.'),
    (918, 'API documentation', 'API Docs', 'DIGITAL', 'Spécification endpoints paramètres réponses.', 'Response parameters endpoints specification API.'),
    (919, 'OpenAPI swagger', 'OpenAPI', 'DIGITAL', 'Spécification standard API format.', 'Format API standard specification openapi.'),
    (920, 'Postman', 'Postman', 'DIGITAL', 'Outil test API requêtes collections.', 'Collections requests API test tool postman.'),
    (921, 'Insomnia', 'Insomnia', 'DIGITAL', 'Client API alternative graphique.', 'Graphical alternative API client insomnia.'),
    (922, 'Swagger UI', 'Swagger', 'DIGITAL', 'Interface documentation interactive API.', 'Interactive API documentation interface.'),
    (923, 'Versioning API', 'API Version', 'DIGITAL', 'Gestion versions rétrocompatibilité deprecated.', 'Deprecated retrocompatibility versions management.'),
    (924, 'Deprecation', 'Deprecated', 'DIGITAL', 'Marquage fin-de-vie notification utilisateurs.', 'User notification end-of-life marking.'),
    (925, 'Migration données', 'Data Migration', 'DIGITAL', 'Transfert données ancien nouveau système.', 'System new old data transfer migration.'),
    (926, 'ETL pipeline', 'ETL', 'DIGITAL', 'Extraction transformation chargement processus.', 'Process loading transformation extraction ETL.'),
    (927, 'Data warehouse', 'Data WH', 'DIGITAL', 'Consolidation agrégation données historiques.', 'Historical data aggregation consolidation repository.'),
    (928, 'Business intelligence', 'BI', 'DIGITAL', 'Analyse données décisions business.', 'Business decisions data analysis intelligence.'),
    (929, 'Analytics', 'Analytics', 'DIGITAL', 'Mesures KPI tableaux bord rapports.', 'Reports dashboards KPI measurements analytics.'),
    (930, 'Machine learning', 'ML', 'DIGITAL', 'Apprentissage statistique prédictions.', 'Statistical learning predictions algorithms ML.'),
    (931, 'Deep learning', 'Deep Learn', 'DIGITAL', 'Réseaux neuronaux apprentissage profond.', 'Deep learning neural networks deep learning.'),
    (932, 'NLP traitement', 'NLP', 'DIGITAL', 'Traitement langage naturel extractiontext.', 'Natural language text extraction processing.'),
    (933, 'Computer vision', 'CV', 'DIGITAL', 'Traitement image reconnaissance pixels.', 'Pixel recognition image processing computer vision.'),
    (934, 'IoT sensors', 'IoT', 'DIGITAL', 'Capteurs objets connectés données.', 'Connected objects data sensors IoT.'),
    (935, 'Edge computing', 'Edge', 'DIGITAL', 'Calcul proche capteur toutes.' , 'Near sensor computation all edge.'),
    (936, 'Blockchain', 'Blockchain', 'DIGITAL', 'Registre décentralisé immuable transactions.', 'Distributed immutable ledger transactions blockchain.'),
    (937, 'Smart contract', 'Smart Cont', 'DIGITAL', 'Code exécution automatique conditions.', 'Automatic condition execution code smart contract.'),
    (938, 'Quantum computing', 'Quantum', 'DIGITAL', 'Calcul quantique supériorité algorithmes.', 'Algorithm supremacy quantum computing calculations.'),
    (939, 'Compliance', 'Compliance', 'DIGITAL', 'Respect normes légales régulations.', 'Legal regulations norms respect compliance.'),
    (940, 'Data governance', 'Governance', 'DIGITAL', 'Politique données qualité propriété.', 'Quality property data ownership policies.'),
    (941, 'Data steward', 'Steward', 'DIGITAL', 'Responsable données qualité intégrité.', 'Data integrity quality responsibility steward.'),
    (942, 'Data quality', 'Data Quality', 'DIGITAL', 'Exactitude complétude validité données.', 'Data validity completeness accuracy quality.'),
    (943, 'Master data', 'Master Data', 'DIGITAL', 'Données référence consolidées immuables.', 'Immutable consolidated reference data master.'),
    (944, 'Data lineage', 'Lineage', 'DIGITAL', 'Traçabilité source transformation données.' , 'Data transformation traceability source lineage.'),
    (945, 'Data catalog', 'Catalog', 'DIGITAL', 'Inventaire métadonnées découvert données.', 'Data discovery metadata inventory catalog.'),
    (946, 'Metadata', 'Metadata', 'DIGITAL', 'Données description données contexte.', 'Context data description metadata information.'),
    (947, 'Semantic web', 'Semantic', 'DIGITAL', 'Web sens signification machine-readable.', 'Machine-readable meaning semantic web sense.'),
    (948, 'Ontology', 'Ontology', 'DIGITAL', 'Vocabulaire relations concepts domaine.', 'Domain concepts relations vocabulary ontology.'),
    (949, 'Linked data', 'Linked Data', 'DIGITAL', 'URI liens données webScale.', 'Web scale linked data URI references.'),
    (950, 'Web 3.0', 'Web3', 'DIGITAL', 'Internet décentralisé blockchain crypto tokens.', 'Crypto tokens blockchain decentralized internet.'),
]

# BATCH 10: Divers & Finition (IDs 951-1000) - 50 terms
batch_10 = [
    (951, 'Viabilité technique', 'Tech Viability', 'DIVERS', 'Faisabilité contrainte ressource possible.', 'Resource constraint feasibility possible viability.'),
    (952, 'Prise décision', 'Decision', 'DIVERS', 'Choix option hiérarchique autorité.', 'Authority hierarchical option choice decision.'),
    (953, 'Consensus', 'Consensus', 'DIVERS', 'Accord unanime parties prenantes.', 'Stakeholder unanimous agreement consensus.'),
    (954, 'Communication interne', 'Internal Comm', 'DIVERS', 'Messages équipe information partage.', 'Information team sharing messages communication.'),
    (955, 'Communication externe', 'External Comm', 'DIVERS', 'Messages public clients partenaires.', 'Partners clients public messages communication.'),
    (956, 'Stakeholder', 'Stakeholder', 'DIVERS', 'Partie prenante intérêt enjeu.', 'Stake concern interested party stakeholder.'),
    (957, 'Change management', 'Change Mgmt', 'DIVERS', 'Gestion modifications adaptation résistance.', 'Adaptation resistance modifications management change.'),
    (958, 'Lesson learned', 'Lessons', 'DIVERS', 'Bilan retours expérience capitalisation.', 'Capitalization experience feedback lessons summary.'),
    (959, 'Post-mortem', 'Post-Mortem', 'DIVERS', 'Analyse décès erreurs incidents.', 'Incidents errors analysis death post-mortem.'),
    (960, 'Retrospective', 'Retro', 'DIVERS', 'Réunion équipe amélioration continue.', 'Continuous improvement team meeting retro.'),
    (961, 'Knowledge base', 'KB', 'DIVERS', 'Dépôt documentation centrale référence.', 'Reference central documentation repository base.'),
    (962, 'Wiki team', 'Wiki', 'DIVERS', 'Plateforme collaborative documentation équipe.', 'Team documentation collaborative platform wiki.'),
    (963, 'Ticket system', 'Tickets', 'DIVERS', 'Suivi problèmes notifications priorisation.', 'Prioritization notifications problems tracking tickets.'),
    (964, 'Bug tracker', 'Bug Track', 'DIVERS', 'Rapport anomalies correction suivi.', 'Follow-up correction anomalies reporting tracker.'),
    (965, 'Enhancement', 'Feature', 'DIVERS', 'Demande amélioration nouvelle fonctionnalité.', 'New functionality improvement request feature.'),
    (966, 'Epic', 'Epic', 'DIVERS', 'Lot grande fonctionnalité décomposition.', 'Large functionality decomposition lot epic.'),
    (967, 'User story', 'User Story', 'DIVERS', 'Description fonctionnalité perspective utilisateur.', 'User perspective functionality description story.'),
    (968, 'Acceptance criteria', 'Criteria', 'DIVERS', 'Conditions validation satisfait récit.', 'Story satisfaction validation conditions criteria.'),
    (969, 'Sprint', 'Sprint', 'DIVERS', 'Itération développement timeline semaine.', 'Week timeline development iteration sprint.'),
    (970, 'Backlog', 'Backlog', 'DIVERS', 'Liste tâches en attente priorisation.', 'Prioritization pending tasks list backlog.'),
    (971, 'Burndown chart', 'Burndown', 'DIVERS', 'Graphique tâches restantes progrès.', 'Progress remaining tasks graph burndown chart.'),
    (972, 'Burnup chart', 'Burnup', 'DIVERS', 'Graphique tâches complétées progression.', 'Progression completed tasks graph burnup.'),
    (973, 'Velocity', 'Velocity', 'DIVERS', 'Capacité équipe par sprint mesure.', 'Measure per sprint capacity team velocity.'),
    (974, 'Estimation planning', 'Estimation', 'DIVERS', 'Points story heures effort.', 'Effort hours story points estimation.'),
    (975, 'Poker planning', 'Poker', 'DIVERS', 'Technique mesure consensus estimation.', 'Estimation consensus measure technique poker.'),
    (976, 'T-shirt sizing', 'T-shirt', 'DIVERS', 'Mesure XS S M L XL.', 'XL L M S sizing shirt estimation.'),
    (977, 'Release', 'Release', 'DIVERS', 'Version produit déploiement production.', 'Production deployment product release version.'),
    (978, 'Hotfix', 'Hotfix', 'DIVERS', 'Correction urgence production branche.', 'Production branch urgent correction hotfix.'),
    (979, 'Rollback', 'Rollback', 'DIVERS', 'Retour version antérieure correction.', 'Prior version return correction rollback.'),
    (980, 'Feature flag', 'Feature Flag', 'DIVERS', 'Switch activation fonctionnalité conditionnelle.', 'Conditional feature activation switch flag.'),
    (981, 'Canary deployment', 'Canary', 'DIVERS', 'Déploiement progressif utilisateurs pourcentage.', 'Percentage users progressive deployment canary.'),
    (982, 'Blue-green', 'Blue-Green', 'DIVERS', 'Environnements parallèles commutation rapide.', 'Quick switch parallel environments blue-green.'),
    (983, 'Infrastructure code', 'IaC', 'DIVERS', 'Infrastructure déclarée code versionnée.', 'Versioned code declared infrastructure as code.'),
    (984, 'Terraform', 'Terraform', 'DIVERS', 'Outil infrastructure cloud provisioning.', 'Cloud provisioning infrastructure tool terraform.'),
    (985, 'Ansible', 'Ansible', 'DIVERS', 'Outil automatisation configuration gestion.', 'Configuration management automation tool ansible.'),
    (986, 'Puppet', 'Puppet', 'DIVERS', 'Plateforme gestion configuration déclarative.', 'Declarative configuration management puppet platform.'),
    (987, 'Chef', 'Chef', 'DIVERS', 'Framework infrastructure automatisation recettes.', 'Recipe automation infrastructure framework chef.'),
    (988, 'SaltStack', 'SaltStack', 'DIVERS', 'Outil orchestration infrastructure configuration.', 'Configuration infrastructure orchestration tool salt.'),
    (989, 'Prometheus', 'Prometheus', 'DIGITAL', 'Système monitoring open-source métrique.', 'Metric open-source monitoring system prometheus.'),
    (990, 'Observabilité', 'Observability', 'DIGITAL', 'Visibility système interne comportement.', 'System internal behavior visibility observability.'),
    (991, 'Incident response', 'IR Team', 'DIVERS', 'Équipe gestion incidents urgence.', 'Emergency incidents management team response.'),
    (992, 'SLA/SLO', 'SLA/SLO', 'DIVERS', 'Accord niveau service objectif.', 'Service level objective agreement SLA.'),
    (993, 'Uptime % ', '99.9%', 'DIVERS', 'Disponibilité service neuf neuf neuf.', 'Service availability nine nine nine.'),
    (994, 'Metrics', 'Metrics', 'DIVERS', 'Mesures indicateurs performance clés.', 'Key performance indicators measures metrics.'),
    (995, 'KPI business', 'KPI', 'DIVERS', 'Performance indicateur commercial affaires.', 'Business commercial performance indicator KPI.'),
    (996, 'ROI', 'ROI', 'DIVERS', 'Investissement retour gain intérêt.', 'Interest gain investment return ROI.'),
    (997, 'TCO', 'TCO', 'DIVERS', 'Coût total possession durée 5ans.', 'Five year duration ownership total cost.'),
    (998, 'Depreciation', 'Depreciation', 'DIVERS', 'Dépréciation valeur équipement temps.', 'Equipment value time depreciation loss.'),
    (999, 'Amortissement', 'Depreciation', 'DIVERS', 'Dépréciation graduelle actifs temps.', 'Asset time gradual depreciation amortization.'),
    (1000, 'Clôture événement', 'Event Closure', 'DIVERS', 'Finalisation administratif archivage complet.', 'Complete archival administrative finalization closure.'),
]

# Combine all batches
all_terms = batch_06 + batch_07 + batch_08 + batch_09 + batch_10

# Generate JavaScript object format
output_lines = []
for id_num, fr, en, cat, def_fr, def_en in all_terms:
    # Escape apostrophes
    fr_escaped = fr.replace("'", "\\'")
    en_escaped = en.replace("'", "\\'")
    def_fr_escaped = def_fr.replace("'", "\\'")
    def_en_escaped = def_en.replace("'", "\\'")
    
    output_lines.append(
        f"  {{id:{id_num},fr:'{fr_escaped}',en:'{en_escaped}',cat:'{cat}',"
        f"def_fr:'{def_fr_escaped}',def_en:'{def_en_escaped}'}},"
    )

# Write to file
with open('/Users/morganspirli/Desktop/aintercom/batch_06_10_terms.txt', 'w') as f:
    f.write('\n'.join(output_lines))

print(f"Generated {len(all_terms)} terms (BATCH 06-10, IDs {all_terms[0][0]}-{all_terms[-1][0]})")
print(f"Output file: /batch_06_10_terms.txt")
